# Site settings THIS IS A COMMENT
title: Hallyma's Web Site
author:
  name: Hallyma Gauthier
  email: 
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
